// Code generated by swaggo/swag. DO NOT EDIT.

package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/steps": {
            "get": {
                "description": "List all supported bifrost steps",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Steps"
                ],
                "summary": "List all bifrost steps",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/opennaslab_io_bifrost_pkg_customapi.StepInfoList"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "opennaslab_io_bifrost_pkg_customapi.Documentation": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/opennaslab_io_bifrost_pkg_customapi.Documentation"
                    }
                },
                "name": {
                    "type": "string"
                },
                "required": {
                    "type": "boolean"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "opennaslab_io_bifrost_pkg_customapi.StepInfo": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "parameters": {
                    "$ref": "#/definitions/opennaslab_io_bifrost_pkg_customapi.StepParameter"
                }
            }
        },
        "opennaslab_io_bifrost_pkg_customapi.StepInfoList": {
            "type": "object",
            "properties": {
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/opennaslab_io_bifrost_pkg_customapi.StepInfo"
                    }
                }
            }
        },
        "opennaslab_io_bifrost_pkg_customapi.StepParameter": {
            "type": "object",
            "properties": {
                "in": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/opennaslab_io_bifrost_pkg_customapi.Documentation"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "bifrost API",
	Description:      "Take you to the land of light, the city of freedom(A unified external service management system for NAS).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
